name: Nightly
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      version:
        description: Nightly version number (e.g. 20221125)
        required: false
        type: string
        default: ''
      language:
        description: Language artefacts
        required: true
        type: choice
        default: "ruby"
        options:
          - java
          - ruby
          - grid

jobs:
  ruby:
    if: inputs.language == 'ruby' || github.event_name == 'schedule'
    name: Ruby
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        gem:
          - selenium-devtools
          - selenium-webdriver
    with:
      name: Release
      cache-key: rb-nightly-${{ matrix.gem }}
      run: |
        export GEM_HOST_API_KEY="Bearer $GITHUB_TOKEN"
        bazel run //rb:${{ matrix.gem }}-bump-nightly-version ${{ inputs.version }}
        bazel run //rb:${{ matrix.gem }}-release-nightly

  java:
    if: inputs.language == 'java' || github.event_name == 'schedule'
    name: Java
    uses: ./.github/workflows/bazel.yml
    with:
      name: Release
      cache-key: java-nightly
      run: |
        ./go publish-maven-snapshot
    secrets: inherit

  grid:
    if: inputs.language == 'grid' || github.event_name == 'schedule'
    name: Grid
    uses: ./.github/workflows/bazel.yml
    with:
      name: Release
      cache-key: grid-nightly
      run: |
        echo build --stamp >>.bazelrc.local
        ./go prep-release-zip
      nightly-release-files: build/dist/*.*
